<?xml version="1.0" encoding="utf-8"?><Database Name="GolfDatabase" Class="GolfStatsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\GolfDatabase.mdf;Integrated Security=True" SettingsObjectName="GolfTracker.My.MySettings" SettingsPropertyName="GolfDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Stats" Member="Stats">
    <Type Name="Stat">
      <Column Name="RoundId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Course" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Course Rating]" Member="Course_Rating" Type="System.Decimal" DbType="Decimal(18,1) NOT NULL" CanBeNull="false" />
      <Column Name="[Slope Rating]" Member="Slope_Rating" Type="System.Decimal" DbType="Decimal(18,1) NOT NULL" CanBeNull="false" />
      <Column Name="GolferId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>